javax:
    sql:
        DataSource:
           AppDataSource:
                dataSourceClassName: com.microsoft.sqlserver.jdbc.SQLServerDataSource
                dataSource:
                    portNumber: 1433
                    password: Qatar2022
                    user: appuser
                    url: jdbc:sqlserver://localhost\SQLEXPRESS;DatabaseName=CustomerDB